### ISSUE TITLE
Crawler script does not work

### ISSUE THREAD

**Issue by ChronosX88** [Arceliar/yggdrasil-map#13]
[crawl-dht.py](https://github.com/Arceliar/yggdrasil-map/blob/master/scripts/crawl-dht.py) does not work. If I try to run, it will give an error:
```
Traceback (most recent call last):
  File "crawler.py", line 57, in <module>
    for k,v in selfInfo['response']['self'].iteritems(): rumored[k] = v
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Сommand that I run it: `python2.7 crawl-dht.py`.

**Comment by Arceliar** [comment]
Thanks. The crawler does need some work. At some point we switched to using a unix socket instead of a tcp stocket for the admin api, so changing your yggdrasil.conf to have `AdminListen: tcp://localhost:9001` *may* fix it for now.

**Comment by ChronosX88** [comment]
> Thanks. The crawler does need some work. At some point we switched to using a unix socket instead of a tcp stocket for the admin api, so changing your yggdrasil.conf to have `AdminListen: tcp://localhost:9001` _may_ fix it for now.

Thanks. I will try it.
