### ISSUE TITLE
Clickable IPv6 links

### ISSUE THREAD

**Issue by cwchristerw** [Arceliar/yggdrasil-map#3]
Example Node:
201:a635:d55c:109e:1f54:d9cc:387e:7963
200:c00f:c8a1:2e17:b7b3:b90:3a72:ffed

Link should not be, because they cannot be clicked when wanting to follow nodelist
http://[21f:dd73:7cdb:773b:a924:7ec0:800b:221e]/#[2%2013]
(aka #[2 13])

it should be like in fc00.org, because it makes possible to click from ipv6 on list
http://[21f:dd73:7cdb:773b:a924:7ec0:800b:221e]/#201:a635:d55c:109e:1f54:d9cc:387e:7963
(aka #201:a635:d55c:109e:1f54:d9cc:387e:7963)

**Comment by Arceliar** [comment]
Think this should be fixed now.
