### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by cwchristerw** [Arceliar/yggdrasil-map#8]
I think it would be nice to have timeline which you can search different stages of network. Yakamo's API need changes because it would have to be possible to search different timestamps.

**Comment by cwchristerw** [comment]
https://github.com/yakamok/Niflheim-api/issues/7

**Comment by Arceliar** [comment]
The info from the API includes timestamps for when nodes were seen (at least, I think that's what the timestamps do), so in theory we could keep our own records of that whenever we pull the `current` list, without needing support added to the API... it would just be inconvenient to do.

**Comment by yakamok** [comment]
Yeah the timestamps are when the node was last seen.

**Comment by cwchristerw** [comment]
> The info from the API includes timestamps for when nodes were seen (at least, I think that's what the timestamps do), so in theory we could keep our own records of that whenever we pull the `current` list, without needing support added to the API... it would just be inconvenient to do.

I think API is the most desirable place to implement because otherwise it needs database backend. It's not good for several reasons. It will show different times for every map instance and therefore API is best solution :smile:

**Comment by yakamok** [comment]
i think this issue should be closed here then.
